baseurl = "https://caseyho.dev"
languageCode = "en-us"
title = "çˆ†è‚å·¥ç¨‹å¸« Casey"
theme = "hugo-tania"
paginate = 5

disqusShortname = "https-hugo-tania-netlify-app"

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "ğŸ‘©â€ğŸ’»"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  #siteName = "Hugo Tania is Amazing"
  #siteDesc = "Hugo is Absurdly Fast!"
  author = "Casey"


  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = "chiayingho.ca@gmail.com"
    facebook = ""
    github = "https://github.com/iosum"
    instagram = ""
    linkedin = "https://www.linkedin.com/in/chiayingho/"
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = ""
    twitch = ""
    whatsapp = ""
  
  # Comments settigns
  [params.comments]
    enabled = true
    provider = "disqus"

[menu]
[[menu.header]]
  name = "æ‰€æœ‰æ–‡ç« "
  url = "/articles/"

  [[menu.footer]]
    name = "Â© 2024"
    weight = 1


[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
