baseurl = "https://caseyho.dev"
languageCode = "en-us"
title = "çˆ†è‚å·¥ç¨‹å¸« Casey"
theme = "hugo-tania"
paginate = 5

disqusShortname = "https-hugo-tania-netlify-app"

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "ğŸ‘©â€ğŸ’»"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  author = "Casey"

  siteName = "çˆ†è‚å·¥ç¨‹å¸« Casey"

  description = "éš¨æ‰‹ç­†è¨˜ã€‚"

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  displayName = ""

  intro = "æˆ‘æ˜¯ä½•ä½³ç© Caseyï¼Œç•¢æ¥­æ–¼éŠ˜å‚³è³‡å·¥ç³»ï¼Œç›®å‰åœ¨ Ringus TW æ“”ä»» OutSystems å·¥ç¨‹å¸«ï¼ŒçœŸå¯¦çš„è‚è‹¦äººã€‚Why å–åç‚ºçˆ†è‚ï¼Œæ˜¯å› ç‚ºå¾110å¹´ç½¹æ‚£è‡ªé«”å…ç–«è‚ç‚åˆ°ç¾åœ¨ï¼Œæ—©å°±ä¸æ˜¯æ–°é®®çš„è‚äº†ğŸ˜‚ğŸ˜‚ğŸ˜‚ï¼Œè©±èªªé†«å­¸ä¸¦æ²’æœ‰çˆ†è‚é€™å€‹è©ï¼Œé€™åªæ˜¯å½¢å®¹æˆ‘çš„è‚ä¸çµ¦åŠ›è€Œå·²ã€‚"


  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = "chiayingho.ca@gmail.com"
    facebook = ""
    github = "https://github.com/iosum"
    instagram = ""
    linkedin = "https://www.linkedin.com/in/chiayingho/"
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = ""
    twitch = ""
    whatsapp = ""


  # Comments settigns
  [params.comments]
    enabled = true
    provider = "disqus"

[menu]
[[menu.header]]
  name = "æ‰€æœ‰æ–‡ç« "
  url = "/articles/"

[[menu.header]]
  name = "é—œæ–¼æˆ‘"
  url = "/about/"

  [[menu.footer]]
    name = "Â© 2024"
    weight = 1


[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
